import type { KontekstGrafiki } from "./typy";
import { domyslneWartosciPol, znajdzSzablon } from "./szablony";
import { zastosujPaczkeGrupy, type GrupaWiejska } from "./szablony-grupy-wiejskie";

export type PaczkaWowGrupy = {
  id: string;
  nazwa: string;
  opis: string;
  grupa: GrupaWiejska;
  emoji: string;
  szablonId: string;
  motywId: string;
  uzupelnienia?: Record<string, string>;
  tytulProjektu?: string;
  badge?: string;
};

export const PACZKI_WOW_GRUPY: PaczkaWowGrupy[] = [
  {
    id: "wow-hubertus",
    nazwa: "Hubertus myśliwski",
    opis: "Msza, korowód, obiad — gotowy program.",
    grupa: "lowiectwo",
    emoji: "🦌",
    szablonId: "lowiectwo-hubertus",
    motywId: "lowiecki-lesny",
    badge: "Popularne",
    tytulProjektu: "Hubertus — zaproszenie",
  },
  {
    id: "wow-dziki",
    nazwa: "Akcja na dziki",
    opis: "Plakat dla rolników i mieszkańców.",
    grupa: "lowiectwo",
    emoji: "🐗",
    szablonId: "lowiectwo-akcja-dziki",
    motywId: "lowiecki-lesny",
    tytulProjektu: "Akcja redukcji dzików",
  },
  {
    id: "wow-festyn-parafia",
    nazwa: "Festyn parafialny",
    opis: "Msza, koncert, stoiska — pełny plakat.",
    grupa: "parafia",
    emoji: "⛪",
    szablonId: "parafia-festyn",
    motywId: "parafia-granat",
    badge: "WOW",
    tytulProjektu: "Festyn parafialny",
  },
  {
    id: "wow-seniorzy-wycieczka",
    nazwa: "Wycieczka seniorów",
    opis: "Autokar, zapisy, data wyjazdu.",
    grupa: "seniorzy",
    emoji: "🚌",
    szablonId: "seniorzy-wycieczka",
    motywId: "seniorzy-cieply",
    tytulProjektu: "Wycieczka klubu seniora",
  },
  {
    id: "wow-turniej-lzs",
    nazwa: "Turniej o Puchar Sołtysa",
    opis: "Piłka, zapisy drużyn, grill po meczach.",
    grupa: "sport",
    emoji: "⚽",
    szablonId: "lzs-turniej",
    motywId: "sport-lzs",
    badge: "WOW",
    tytulProjektu: "Turniej LZS",
  },
  {
    id: "wow-rada-otwarte",
    nazwa: "Otwarte posiedzenie rady",
    opis: "Dla sołtysa — transparentność wobec wsi.",
    grupa: "rada",
    emoji: "🏛️",
    szablonId: "rada-spotkanie",
    motywId: "klasyczny-bialy",
    tytulProjektu: "Posiedzenie Rady Sołeckiej",
  },
  {
    id: "wow-wspolna-akcja",
    nazwa: "OSP + KGW + Parafia",
    opis: "Jeden plakat — cała wieś razem.",
    grupa: "mix",
    emoji: "🤝",
    szablonId: "mix-wspolna-akcja",
    motywId: "zielony-wies",
    badge: "WOW",
    tytulProjektu: "Wspólna akcja charytatywna",
    uzupelnienia: {
      opis: "Wspólnie: OSP · KGW · Parafia · Sołectwo {{wies}}\n• Kiermasz i stoiska\n• Koncert na scenie\n• Całodzienny piknik rodzinny",
    },
  },
  {
    id: "wow-podziekowanie-rolnik",
    nazwa: "Podziękowanie dla rolnika",
    opis: "Od koła łowieckiego — dobre relacje na wsi.",
    grupa: "lowiectwo",
    emoji: "🌾",
    szablonId: "lowiectwo-podziekowanie-rolnik",
    motywId: "lowiecki-lesny",
    tytulProjektu: "Podziękowanie dla rolnika",
  },
  {
    id: "wow-konkurs-szkola",
    nazwa: "Konkurs szkolny — dyplom",
    opis: "Plastyczny / recytatorski — gotowy dyplom.",
    grupa: "dyplomy",
    emoji: "🎨",
    szablonId: "szkola-konkurs",
    motywId: "turkusowy-letni",
    tytulProjektu: "Dyplom konkursu",
  },
  {
    id: "wow-zespol-wystep",
    nazwa: "Występ zespołu ludowego",
    opis: "Koncert na scenie — plakat z repertuarem.",
    grupa: "zespol",
    emoji: "💃",
    szablonId: "zespol-wystep",
    motywId: "folklor-kolorowy",
    badge: "WOW",
    tytulProjektu: "Koncert zespołu ludowego",
  },
  {
    id: "wow-zespol-proba",
    nazwa: "Próba zespołu — rekrutacja",
    opis: "Zachęć nowych członków do dołączenia.",
    grupa: "zespol",
    emoji: "🪗",
    szablonId: "zespol-proba",
    motywId: "folklor-kolorowy",
    tytulProjektu: "Próba zespołu ludowego",
  },
  {
    id: "wow-ddk-warsztaty",
    nazwa: "Warsztaty DDK / GOPS",
    opis: "Zajęcia dla seniorów i rodzin — zapisy.",
    grupa: "ddk",
    emoji: "🏛️",
    szablonId: "ddk-warsztaty",
    motywId: "ddk-gops-niebieski",
    badge: "WOW",
    tytulProjektu: "Warsztaty w DDK",
  },
  {
    id: "wow-gops-pomoc",
    nazwa: "Punkt informacyjny GOPS",
    opis: "Plakat o pomocy społecznej i konsultacjach.",
    grupa: "ddk",
    emoji: "🤝",
    szablonId: "ddk-pomoc-spoleczna",
    motywId: "ddk-gops-niebieski",
    tytulProjektu: "Informacja GOPS",
  },
  {
    id: "wow-sponsor-plakat",
    nazwa: "Patroni imprezy",
    opis: "Lista sponsorów na plakacie festynu.",
    grupa: "sponsor",
    emoji: "⭐",
    szablonId: "sponsor-plakat",
    motywId: "sponsor-zloto",
    badge: "WOW",
    tytulProjektu: "Patroni festynu",
  },
  {
    id: "wow-sponsor-dziekuje",
    nazwa: "Podziękowanie sponsorowi",
    opis: "Oficjalne podziękowanie po imprezie.",
    grupa: "sponsor",
    emoji: "🙏",
    szablonId: "sponsor-podziekowanie",
    motywId: "sponsor-zloto",
    tytulProjektu: "Podziękowanie dla sponsora",
  },
  {
    id: "wow-dwujezyczne-impreza",
    nazwa: "Impreza PL + UA",
    opis: "Zaproszenie po polsku i ukraińsku.",
    grupa: "mix",
    emoji: "🇵🇱🇺🇦",
    szablonId: "dwujezyczne-zaproszenie-impreza",
    motywId: "nowoczesny-granat",
    badge: "WOW",
    tytulProjektu: "Spotkanie integracyjne PL+UA",
  },
  {
    id: "wow-dni-seniora",
    nazwa: "Dni Seniora",
    opis: "Uroczystość dla klubu seniora.",
    grupa: "seniorzy",
    emoji: "🌻",
    szablonId: "sezon-dni-seniora",
    motywId: "seniorzy-cieply",
    tytulProjektu: "Dni Seniora",
  },
  {
    id: "wow-sylwester",
    nazwa: "Sylwester w świetlicy",
    opis: "Plakat na zabawę noworoczną.",
    grupa: "mix",
    emoji: "🎇",
    szablonId: "sezon-sylwester",
    motywId: "wow-festyn",
    tytulProjektu: "Sylwester",
  },
  {
    id: "wow-biblioteka",
    nazwa: "Spotkanie w bibliotece",
    opis: "Klub czytelniczy — warsztaty i czytanie.",
    grupa: "szkola",
    emoji: "📚",
    szablonId: "biblioteka-spotkanie",
    motywId: "turkusowy-letni",
    tytulProjektu: "Klub czytelniczy",
  },
  {
    id: "wow-dyplom-osp",
    nazwa: "Dyplom OSP — weteran",
    opis: "Wieloletnia służba w straży pożarnej.",
    grupa: "dyplomy",
    emoji: "🚒",
    szablonId: "dyplom-osp-weteran",
    motywId: "osp-czerwony",
    badge: "NOWY",
    tytulProjektu: "Dyplom weterana OSP",
  },
  {
    id: "wow-dyplom-wolontariusz",
    nazwa: "Dyplom wolontariusza",
    opis: "Po festynie lub akcji charytatywnej.",
    grupa: "dyplomy",
    emoji: "💚",
    szablonId: "dyplom-wolontariusz",
    motywId: "zielony-wies",
    tytulProjektu: "Dyplom wolontariusza",
  },
  {
    id: "wow-dyplom-zasluzony",
    nazwa: "Zasłużony mieszkaniec",
    opis: "Honorowe wyróżnienie od sołtysa.",
    grupa: "dyplomy",
    emoji: "🏅",
    szablonId: "dyplom-zasluzony-mieszkaniec",
    motywId: "klasyczny-bialy",
    badge: "WOW",
    tytulProjektu: "Dyplom honorowy",
  },
  {
    id: "wow-dyplom-sport",
    nazwa: "Mistrz turnieju",
    opis: "Po meczu finałowym LZS.",
    grupa: "dyplomy",
    emoji: "🏆",
    szablonId: "dyplom-sport-mistrz",
    motywId: "sport-lzs",
    tytulProjektu: "Dyplom mistrza",
  },
  {
    id: "wow-dyplom-parafia",
    nazwa: "Ministranci — dyplom",
    opis: "Za służbę liturgiczną w parafii.",
    grupa: "dyplomy",
    emoji: "⛪",
    szablonId: "dyplom-parafia-ministrans",
    motywId: "parafia-granat",
    tytulProjektu: "Dyplom ministranta",
  },
  {
    id: "wow-dyplom-lowca",
    nazwa: "Łowca Roku",
    opis: "Wyróżnienie koła łowieckiego.",
    grupa: "dyplomy",
    emoji: "🦌",
    szablonId: "dyplom-lowca-roku",
    motywId: "lowiecki-lesny",
    tytulProjektu: "Łowca Roku",
  },
  {
    id: "wow-dyplom-patriotyczny",
    nazwa: "Konkurs patriotyczny",
    opis: "Święto Niepodległości — dyplom dla ucznia.",
    grupa: "dyplomy",
    emoji: "🇵🇱",
    szablonId: "dyplom-patriotyczny",
    motywId: "elegancki-zloty",
    tytulProjektu: "Dyplom konkursu",
  },
  {
    id: "wow-dzien-dziecka",
    nazwa: "Dzień Dziecka — plakat",
    opis: "Piknik rodzinny na boisku.",
    grupa: "szkola",
    emoji: "🎈",
    szablonId: "plakat-dzien-dziecka-kolorowy",
    motywId: "dzieci-radosny",
    tytulProjektu: "Dzień Dziecka",
  },
  {
    id: "wow-wigilia-wies",
    nazwa: "Wigilia wiejska",
    opis: "Wspólny opłatek w świetlicy.",
    grupa: "mix",
    emoji: "🕯️",
    szablonId: "plakat-wigilia-wies",
    motywId: "elegancki-zloty",
    tytulProjektu: "Wigilia mieszkańców",
  },
  {
    id: "wow-dyplom-fundator",
    nazwa: "Dyplom fundatora",
    opis: "Dla firmy wspierającej wieś — pergamin premium.",
    grupa: "dyplomy",
    emoji: "🤝",
    szablonId: "dyplom-fundator-wsi",
    motywId: "elegancki-zloty",
    badge: "NOWY",
    tytulProjektu: "Dyplom fundatora",
  },
  {
    id: "wow-certyfikat-sponsor",
    nazwa: "Certyfikat sponsora festynu",
    opis: "Partner imprezy — układ medal.",
    grupa: "dyplomy",
    emoji: "⭐",
    szablonId: "certyfikat-partner-imprezy",
    motywId: "sponsor-zloto",
    tytulProjektu: "Certyfikat partnera",
  },
  {
    id: "wow-kronika-wsi",
    nazwa: "Kronika wsi — plakat",
    opis: "Spotkanie wspominkowe, zdjęcia archiwalne.",
    grupa: "seniorzy",
    emoji: "📷",
    szablonId: "plakat-kronika-wsi",
    motywId: "seniorzy-cieply",
    tytulProjektu: "Kronika wsi",
  },
  {
    id: "wow-dzien-dziecka-kolor",
    nazwa: "Dzień Dziecka — kolorowy plakat",
    opis: "Balony, animacje, konkursy — gotowy program.",
    grupa: "szkola",
    emoji: "🎈",
    szablonId: "plakat-dzien-dziecka-kolorowy",
    motywId: "dzieci-radosny",
    badge: "MAJ",
    tytulProjektu: "Dzień Dziecka",
  },
  {
    id: "wow-dzien-dziecka-swietlica",
    nazwa: "Dzień Dziecka w świetlicy",
    opis: "Impreza w sali wiejskiej — teatrzyk, warsztaty.",
    grupa: "mix",
    emoji: "🎭",
    szablonId: "plakat-dzien-dziecka-swietlica",
    motywId: "dzieci-radosny",
    tytulProjektu: "Dzień Dziecka — świetlica",
  },
  {
    id: "wow-konkurs-plastyczny",
    nazwa: "Konkurs plastyczny dla dzieci",
    opis: "Ogłoszenie + dyplom w pakiecie.",
    grupa: "szkola",
    emoji: "🎨",
    szablonId: "plakat-konkurs-plastyczny-dzieci",
    motywId: "dzieci-radosny",
    tytulProjektu: "Konkurs plastyczny",
  },
  {
    id: "wow-regulamin-swietlicy",
    nazwa: "Regulamin świetlicy — karta",
    opis: "Gotowe zasady do powieszenia przy wejściu.",
    grupa: "mix",
    emoji: "📋",
    szablonId: "karta-regulamin-swietlicy",
    motywId: "swietlica-ciepla",
    badge: "NOWY",
    tytulProjektu: "Regulamin świetlicy",
  },
  {
    id: "wow-godziny-swietlicy",
    nazwa: "Godziny otwarcia świetlicy",
    opis: "Plakat z harmonogramem zajęć tygodniowych.",
    grupa: "mix",
    emoji: "🏠",
    szablonId: "plakat-godziny-swietlicy",
    motywId: "swietlica-ciepla",
    tytulProjektu: "Godziny świetlicy",
  },
  {
    id: "wow-rezerwacja-swietlicy",
    nazwa: "Rezerwacja sali — zasady",
    opis: "Karta dla mieszkańców chcących wypożyczyć salę.",
    grupa: "mix",
    emoji: "🗓️",
    szablonId: "karta-rezerwacja-swietlicy",
    motywId: "swietlica-ciepla",
    tytulProjektu: "Rezerwacja świetlicy",
  },
  {
    id: "wow-otwarcie-swietlicy",
    nazwa: "Otwarcie odnowionej świetlicy",
    opis: "Zaproszenie po remoncie z funduszu sołeckiego.",
    grupa: "mix",
    emoji: "✨",
    szablonId: "zaproszenie-otwarcie-swietlicy",
    motywId: "swietlica-ciepla",
    tytulProjektu: "Otwarcie świetlicy",
  },
  {
    id: "wow-zebranie-tablica",
    nazwa: "Zebranie — plakat tablicowy",
    opis: "Czytelne ogłoszenie z datą i porządkiem obrad.",
    grupa: "rada",
    emoji: "📋",
    szablonId: "plakat-zebranie-tablica",
    motywId: "tablica-czerwony",
    badge: "NOWY",
    tytulProjektu: "Zebranie wiejskie",
  },
  {
    id: "wow-fundusz-sołecki",
    nazwa: "Fundusz sołecki — plan",
    opis: "Lista zadań i kwot do tablicy ogłoszeń.",
    grupa: "rada",
    emoji: "💰",
    szablonId: "plakat-fundusz-sołecki",
    motywId: "zielony-wies",
    tytulProjektu: "Plan funduszu sołeckiego",
  },
  {
    id: "wow-program-festynu",
    nazwa: "Program festynu / dożynków",
    opis: "Rozkład godzinowy przy scenie.",
    grupa: "mix",
    emoji: "🎪",
    szablonId: "karta-program-festynu",
    motywId: "wow-festyn",
    tytulProjektu: "Program festynu",
  },
  {
    id: "wow-11-listopada",
    nazwa: "11 listopada — uroczystość",
    opis: "Patriotyczny plakat z programem mszy i koncertu.",
    grupa: "mix",
    emoji: "🇵🇱",
    szablonId: "plakat-11-listopada",
    motywId: "patriotyczny-granat",
    tytulProjektu: "Święto Niepodległości",
  },
  {
    id: "wow-kiermasz-jesien",
    nazwa: "Kiermasz jesienny KGW",
    opis: "Plakat stoisk, ciast i rękodzieła.",
    grupa: "szkola",
    emoji: "🥧",
    szablonId: "plakat-kiermasz-jesien",
    motywId: "kgw-rozowy",
    tytulProjektu: "Kiermasz KGW",
  },
  {
    id: "wow-kontakt-solectwa",
    nazwa: "Karta kontaktowa sołectwa",
    opis: "Telefony sołtysa, OSP, świetlicy — do sklepu.",
    grupa: "rada",
    emoji: "📞",
    szablonId: "karta-kontakt-solectwa",
    motywId: "zielony-wies",
    tytulProjektu: "Kontakt sołectwa",
  },
];

export type WynikPaczkiWow = {
  szablonId: string;
  motywId: string;
  wartosci: Record<string, string>;
  tytulProjektu: string;
};

export function zbudujZPaczkiWow(paczka: PaczkaWowGrupy, kontekst: KontekstGrafiki): WynikPaczkiWow | null {
  const szablon = znajdzSzablon(paczka.szablonId);
  if (!szablon) return null;
  const bazowe = domyslneWartosciPol(szablon, kontekst);
  const nadpisane = paczka.uzupelnienia ? zastosujPaczkeGrupy(paczka.uzupelnienia, kontekst) : {};
  return {
    szablonId: paczka.szablonId,
    motywId: paczka.motywId,
    wartosci: { ...bazowe, ...nadpisane },
    tytulProjektu: paczka.tytulProjektu ?? szablon.tytul,
  };
}

export function paczkiWowDlaGrupy(grupa: GrupaWiejska): PaczkaWowGrupy[] {
  if (grupa === "wszystkie") return PACZKI_WOW_GRUPY;
  return PACZKI_WOW_GRUPY.filter((p) => p.grupa === grupa);
}
