import type { SzablonGrafiki } from "./typy";

/** Zaproszenia i plakaty z treścią po polsku i ukraińsku (dla gości z Ukrainy). */
export const SZABLONY_DWujezyczne: SzablonGrafiki[] = [
  {
    id: "dwujezyczne-zaproszenie-impreza",
    kategoria: "zaproszenia",
    tytul: "Zaproszenie PL + UA (impreza)",
    opis: "Polski i ukraiński na jednym plakacie — festyn, spotkanie, kiermasz.",
    layout: "zaproszenie-dwujezyczne",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek (PL)", typ: "text", domysl: "Serdecznie zapraszamy" },
      { id: "naglowek_ua", etykieta: "Nagłówek (UA)", typ: "text", domysl: "Щиро запрошуємо" },
      { id: "tytul", etykieta: "Tytuł (PL)", typ: "text", domysl: "Spotkanie integracyjne — {{wies}}" },
      { id: "tytul_ua", etykieta: "Tytuł (UA)", typ: "text", domysl: "Інтеграційна зустріч — {{wies}}" },
      {
        id: "opis",
        etykieta: "Opis (PL)",
        typ: "textarea",
        domysl: "Wspólne świętowanie, jedzenie, muzyka i rozmowy dla wszystkich mieszkańców.",
      },
      {
        id: "opis_ua",
        etykieta: "Opis (UA)",
        typ: "textarea",
        domysl: "Спільне святкування, їжа, музика та розмови для всіх мешканців.",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "16:00" },
      { id: "miejsce", etykieta: "Miejsce (PL)", typ: "text", domysl: "Świetlica wiejska, {{wies}}" },
      { id: "miejsce_ua", etykieta: "Miejsce (UA)", typ: "text", domysl: "Сільський будинок культури, {{wies}}" },
      { id: "organizator", etykieta: "Organizator (PL)", typ: "text", domysl: "Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "nowoczesny-granat",
    dostep: "wszyscy",
    tagi: ["ukraiński", "UA", "dwujęzyczny", "integracja"],
  },
  {
    id: "dwujezyczne-plakat-pomoc",
    kategoria: "plakaty",
    tytul: "Plakat informacyjny PL + UA",
    opis: "Ważna informacja dla wszystkich — np. zbiórka, pomoc, zebranie.",
    layout: "zaproszenie-dwujezyczne",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło (PL)", typ: "text", domysl: "Ważna informacja" },
      { id: "naglowek_ua", etykieta: "Hasło (UA)", typ: "text", domysl: "Важлива інформація" },
      { id: "tytul", etykieta: "Tytuł (PL)", typ: "text", domysl: "Komunikat dla mieszkańców {{wies}}" },
      { id: "tytul_ua", etykieta: "Tytuł (UA)", typ: "text", domysl: "Повідомлення для мешканців {{wies}}" },
      {
        id: "opis",
        etykieta: "Treść (PL)",
        typ: "textarea",
        domysl: "Prosimy o zapoznanie się z informacją i przekazanie sąsiadom.",
      },
      {
        id: "opis_ua",
        etykieta: "Treść (UA)",
        typ: "textarea",
        domysl: "Будь ласка, ознайомтеся з інформацією та передайте сусідам.",
      },
      { id: "data", etykieta: "Data (opcjonalnie)", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "" },
      { id: "miejsce", etykieta: "Miejsce (PL)", typ: "text", domysl: "{{wies}}" },
      { id: "miejsce_ua", etykieta: "Miejsce (UA)", typ: "text", domysl: "{{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "{{organizator}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "ddk-gops-niebieski",
    dostep: "wszyscy",
    tagi: ["ukraiński", "UA", "plakat"],
  },
  {
    id: "dwujezyczne-zebranie",
    kategoria: "zaproszenia",
    tytul: "Zebranie wiejskie PL + UA",
    opis: "Zaproszenie mieszkańców — także w języku ukraińskim.",
    layout: "zaproszenie-dwujezyczne",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek (PL)", typ: "text", domysl: "Zaproszenie na zebranie" },
      { id: "naglowek_ua", etykieta: "Nagłówek (UA)", typ: "text", domysl: "Запрошення на збори" },
      { id: "tytul", etykieta: "Tytuł (PL)", typ: "text", domysl: "Zebranie wiejskie sołectwa {{wies}}" },
      { id: "tytul_ua", etykieta: "Tytuł (UA)", typ: "text", domysl: "Сільські збори {{wies}}" },
      {
        id: "opis",
        etykieta: "Porządek (PL)",
        typ: "textarea",
        domysl: "1. Otwarcie\n2. Sprawy bieżące\n3. Sprawy różne",
      },
      {
        id: "opis_ua",
        etykieta: "Porządek (UA)",
        typ: "textarea",
        domysl: "1. Відкриття\n2. Поточні справи\n3. Різне",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "18:00" },
      { id: "miejsce", etykieta: "Miejsce (PL)", typ: "text", domysl: "Świetlica, {{wies}}" },
      { id: "miejsce_ua", etykieta: "Miejsce (UA)", typ: "text", domysl: "Будинок культури, {{wies}}" },
      { id: "organizator", etykieta: "Zaprasza", typ: "text", domysl: "Sołtys {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "klasyczny-bialy",
    dostep: "soltys",
    tagi: ["ukraiński", "zebranie", "sołectwo"],
  },
];
