import type { KontekstGrafiki, SzablonGrafiki } from "./typy";
import { uzupelnijPlaceholdery } from "./szablony";

/** Szablony dla kół łowieckich, parafii, seniorów, LZS i innych grup wiejskich */
export const SZABLONY_GRUP_WIEJSKICH: SzablonGrafiki[] = [
  {
    id: "lowiectwo-hubertus",
    kategoria: "zaproszenia",
    tytul: "Hubertus / uroczystość łowiecka",
    opis: "Zaproszenie na mszę hubertowską, obiad i spotkanie koła łowieckiego.",
    layout: "zaproszenie-lesne",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Koło Łowieckie zaprasza" },
      { id: "tytul", etykieta: "Nazwa uroczystości", typ: "text", domysl: "Hubertus 2026" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl:
          "Msza św. w intencji myśliwych · korowód · wspólny posiłek · wręczenie odznaczeń · gościnność do późnego wieczora.",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "10:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Koło Łowieckie, okolice {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Koło Łowieckie „…”, {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "lowiecki-lesny",
    dostep: "wszyscy",
    tagi: ["łowiectwo", "hubertus", "myśliwi", "wow"],
  },
  {
    id: "lowiectwo-zebranie",
    kategoria: "zaproszenia",
    tytul: "Zebranie koła łowieckiego",
    opis: "Walne zebranie, podsumowanie sezonu, wybory zarządu.",
    layout: "zaproszenie-lesne",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Zaproszenie na zebranie" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Walne zebranie członków koła" },
      {
        id: "opis",
        etykieta: "Porządek",
        typ: "textarea",
        domysl: "1. Otwarcie\n2. Sprawozdanie zarządu\n3. Finanse i plan na nowy sezon\n4. Sprawy różne\n5. Zakończenie",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "18:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Dom myśliwskiego / świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Zaprasza", typ: "text", domysl: "Zarząd Koła Łowieckiego" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "lowiecki-lesny",
    dostep: "wszyscy",
    tagi: ["łowiectwo", "zebranie"],
  },
  {
    id: "lowiectwo-akcja-dziki",
    kategoria: "plakaty",
    tytul: "Plakat — akcja na dziki / ochrona pól",
    opis: "Informacja dla rolników i mieszkańców o akcji koła łowieckiego.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Współpraca dla bezpieczeństwa pól" },
      { id: "tytul", etykieta: "Tytuł akcji", typ: "text", domysl: "Akcja redukcji dzików" },
      {
        id: "opis",
        etykieta: "Treść",
        typ: "textarea",
        domysl:
          "Koło łowieckie informuje o planowanych polowaniach redukcyjnych.\nProsimy o nie wchodzenie w oznaczone rejonu.\nKontakt do łowczych: tel. …",
      },
      { id: "data", etykieta: "Termin", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godziny", typ: "time", domysl: "od świtu" },
      { id: "miejsce", etykieta: "Rejon", typ: "text", domysl: "Obwód łowiecki — {{wies}} i okolice" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Koło Łowieckie {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "lowiecki-lesny",
    dostep: "wszyscy",
    tagi: ["łowiectwo", "dziki", "rolnictwo"],
  },
  {
    id: "parafia-festyn",
    kategoria: "plakaty",
    tytul: "Festyn parafialny",
    opis: "Plakat na dożynki parafialne, kiermasz, koncert.",
    layout: "zaproszenie-parafialne",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Parafia {{wies}} zaprasza" },
      { id: "tytul", etykieta: "Nazwa", typ: "text", domysl: "Festyn parafialny" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "• Msza św. na placu\n• Koncert scholi\n• Stoiska KGW i OSP\n• Losowanie nagród",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "12:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Przy kościele, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Parafia pw. … · Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. kancelarii …" },
    ],
    domyslnyMotyw: "parafia-granat",
    dostep: "wszyscy",
    tagi: ["parafia", "festyn", "wow"],
  },
  {
    id: "parafia-msza-rocznicowa",
    kategoria: "zaproszenia",
    tytul: "Zaproszenie na mszę / uroczystość",
    opis: "Rocznica parafii, bierzmowanie, procesja.",
    layout: "zaproszenie-parafialne",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Serdecznie zapraszamy" },
      { id: "tytul", etykieta: "Okazja", typ: "text", domysl: "Msza dziękczynna za …" },
      { id: "opis", etykieta: "Informacje", typ: "textarea", domysl: "Po mszy wspólne spotkanie przy kościele — poczęstunek dla mieszkańców." },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "11:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Kościół parafialny, {{wies}}" },
      { id: "organizator", etykieta: "Zaprasza", typ: "text", domysl: "Parafia {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "parafia-granat",
    dostep: "wszyscy",
    tagi: ["parafia", "msza"],
  },
  {
    id: "seniorzy-wycieczka",
    kategoria: "zaproszenia",
    tytul: "Wycieczka klubu seniora",
    opis: "Zaproszenie seniorów na wycieczkę autokarem.",
    layout: "zaproszenie-rustykalne",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Klub Seniora zaprasza!" },
      { id: "tytul", etykieta: "Cel wycieczki", typ: "text", domysl: "Wycieczka do …" },
      { id: "opis", etykieta: "Szczegóły", typ: "textarea", domysl: "Wyjazd autokarem · zwiedzanie · obiad · powrót tego samego dnia. Zapisy u sołtysa." },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina wyjazdu", typ: "time", domysl: "8:00" },
      { id: "miejsce", etykieta: "Miejsce zbiórki", typ: "text", domysl: "Przy świetlicy, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Klub Seniora {{wies}}" },
      { id: "kontakt", etykieta: "Zapisy", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "seniorzy-cieply",
    dostep: "wszyscy",
    tagi: ["seniorzy", "wycieczka", "wow"],
  },
  {
    id: "seniorzy-zajecia",
    kategoria: "karty",
    tytul: "Harmonogram zajęć seniorów",
    opis: "Karta z planem cotygodniowych spotkań.",
    layout: "karta-informacyjna",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Tytuł", typ: "text", domysl: "Klub Seniora — plan zajęć" },
      { id: "tytul", etykieta: "Podtytuł", typ: "text", domysl: "{{wies}}" },
      {
        id: "opis",
        etykieta: "Harmonogram",
        typ: "textarea",
        domysl: "• Wtorek 10:00 — gimnastyka\n• Czwartek 15:00 — tańce i karaoke\n• Piątek 14:00 — gry planszowe\nWstęp wolny dla mieszkańców 60+",
      },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
      { id: "organizator", etykieta: "Stopka", typ: "text", domysl: "Sołectwo {{wies}} · współpraca z GOPS" },
    ],
    domyslnyMotyw: "seniorzy-cieply",
    dostep: "wszyscy",
    tagi: ["seniorzy"],
  },
  {
    id: "lzs-turniej",
    kategoria: "plakaty",
    tytul: "Turniej LZS / piłka nożna",
    opis: "Plakat na turniej wiejskich drużyn.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Sport łączy wieś!" },
      { id: "tytul", etykieta: "Nazwa turnieju", typ: "text", domysl: "Turniej o Puchar Sołtysa" },
      {
        id: "opis",
        etykieta: "Regulamin skrót",
        typ: "textarea",
        domysl: "• Drużyny 7-osobowe\n• Zapisy do …\n• Nagrody dla 3 pierwszych miejsc\n• Po turnieju grill dla kibiców",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Początek", typ: "time", domysl: "15:00" },
      { id: "miejsce", etykieta: "Boisko", typ: "text", domysl: "Orlik / boisko, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · LZS" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "sport-lzs",
    dostep: "wszyscy",
    tagi: ["sport", "LZS", "turniej", "wow"],
  },
  {
    id: "rada-spotkanie",
    kategoria: "zaproszenia",
    tytul: "Spotkanie Rady Sołeckiej",
    opis: "Zaproszenie mieszkańców na otwarte posiedzenie rady.",
    layout: "zaproszenie-eleganckie",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Rada Sołecka zaprasza" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Otwarte posiedzenie Rady Sołeckiej {{wies}}" },
      { id: "opis", etykieta: "Tematy", typ: "textarea", domysl: "Omówienie planu zadań, funduszu sołeckiego i inwestycji w roku bieżącym." },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "17:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Przewodniczący", typ: "text", domysl: "Rada Sołecka {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. sołtysa …" },
    ],
    domyslnyMotyw: "klasyczny-bialy",
    dostep: "soltys",
    tagi: ["rada", "sołectwo"],
  },
  {
    id: "szkola-konkurs",
    kategoria: "dyplomy",
    tytul: "Dyplom — konkurs szkolny / biblioteka",
    opis: "Konkurs recytatorski, plastyczny, czytelniczy.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Dyplom uznania" },
      { id: "tytul", etykieta: "Imię i nazwisko", typ: "text", domysl: "…" },
      { id: "opis", etykieta: "Za co", typ: "textarea", domysl: "Za udział w konkursie „Wiersz o mojej wsi” organizowanym przez szkołę i bibliotekę." },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "{{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Szkoła Podstawowa · Biblioteka Publiczna" },
      { id: "podpis1", etykieta: "Podpis", typ: "text", domysl: "Dyrektor szkoły\n…" },
      { id: "podpis2", etykieta: "Podpis 2", typ: "text", domysl: "Sołtys\n…" },
    ],
    domyslnyMotyw: "turkusowy-letni",
    dostep: "wszyscy",
    tagi: ["szkoła", "biblioteka", "konkurs"],
  },
  {
    id: "mix-wspolna-akcja",
    kategoria: "plakaty",
    tytul: "Wspólna akcja organizacji wsi",
    opis: "OSP + KGW + sołectwo + parafia — jeden plakat.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Razem dla {{wies}}!" },
      { id: "tytul", etykieta: "Nazwa akcji", typ: "text", domysl: "Wielka akcja charytatywna" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl:
          "Wspólnie: OSP · KGW · Parafia · Sołectwo\n• Kiermasz domowych produktów\n• Koncert\n• Zbiórka na cel charytatywny",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "14:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Plac przy świetlicy, {{wies}}" },
      { id: "organizator", etykieta: "Organizatorzy", typ: "text", domysl: "Organizacje {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "zielony-wies",
    dostep: "wszyscy",
    tagi: ["mix", "charytatywna", "wow", "OSP", "KGW"],
  },
  {
    id: "lowiectwo-podziekowanie-rolnik",
    kategoria: "podziekowania",
    tytul: "Podziękowanie dla rolnika (współpraca)",
    opis: "Koło łowieckie dziękuje za udostępnienie łąk i współpracę.",
    layout: "podziekowanie",
    format: "a5",
    orientacja: "poziom",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Podziękowanie" },
      { id: "tytul", etykieta: "Dla kogo", typ: "text", domysl: "Gospodarstwo …" },
      {
        id: "opis",
        etykieta: "Treść",
        typ: "textarea",
        domysl: "Za życzliwość, udostępnianie gruntów i współpracę przy redukcji szkód dzikich — serdecznie dziękujemy.",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "{{wies}}" },
      { id: "organizator", etykieta: "W imieniu", typ: "text", domysl: "Koło Łowieckie {{wies}}" },
      { id: "podpis1", etykieta: "Podpis", typ: "text", domysl: "Prezes koła\n…" },
    ],
    domyslnyMotyw: "lowiecki-lesny",
    dostep: "wszyscy",
    tagi: ["łowiectwo", "rolnictwo"],
  },
  {
    id: "zespol-wystep",
    kategoria: "plakaty",
    tytul: "Plakat — występ zespołu ludowego",
    opis: "Koncert, dożynki, festyn — zespół pieśni i tańca.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Zespół Ludowy zaprasza" },
      { id: "tytul", etykieta: "Nazwa występu", typ: "text", domysl: "Koncert folklorystyczny" },
      {
        id: "opis",
        etykieta: "Program / repertuar",
        typ: "textarea",
        domysl: "Tańce regionalne · pieśni ludowe · wspólna zabawa przy muzyce na żywo",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "18:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Scena / świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Zespół Ludowy „…”, {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "folklor-kolorowy",
    dostep: "wszyscy",
    tagi: ["zespół", "folklor", "taniec", "muzyka"],
  },
  {
    id: "zespol-proba",
    kategoria: "zaproszenia",
    tytul: "Zaproszenie na próbę zespołu",
    opis: "Rekrutacja do zespołu pieśni i tańca — nowi członkowie mile widziani.",
    layout: "zaproszenie-rustykalne",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Dołącz do nas!" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Próba zespołu ludowego" },
      {
        id: "opis",
        etykieta: "Informacje",
        typ: "textarea",
        domysl: "Zapraszamy osoby w każdym wieku — nie trzeba umieć tańczyć od razu. Przyjdź poznać naszą społeczność.",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "17:30" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Prowadzący", typ: "text", domysl: "Zespół Ludowy {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "folklor-kolorowy",
    dostep: "wszyscy",
    tagi: ["zespół", "folklor", "próba"],
  },
  {
    id: "ddk-warsztaty",
    kategoria: "plakaty",
    tytul: "Warsztaty w DDK / GOPS",
    opis: "Zajęcia dla seniorów, rodzin, dorosłych — finansowane z budżetu obywatelskiego.",
    layout: "karta-informacyjna",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Dom Kultury / GOPS zaprasza" },
      { id: "tytul", etykieta: "Nazwa warsztatów", typ: "text", domysl: "Warsztaty kreatywne" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "Zajęcia bezpłatne · materiały zapewnione · zapisy w sekretariacie · liczba miejsc ograniczona",
      },
      { id: "data", etykieta: "Data rozpoczęcia", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "10:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "DDK / GOPS, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "GOPS {{gmina}} · Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Zapisy", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "ddk-gops-niebieski",
    dostep: "wszyscy",
    tagi: ["ddk", "gops", "warsztaty", "seniorzy"],
  },
  {
    id: "ddk-pomoc-spoleczna",
    kategoria: "plakaty",
    tytul: "Informacja — pomoc społeczna",
    opis: "Plakat o dostępnych świadczeniach, konsultacjach, wsparciu rodzin.",
    layout: "karta-informacyjna",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Potrzebujesz wsparcia?" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Punkt informacyjny GOPS" },
      {
        id: "opis",
        etykieta: "Treść",
        typ: "textarea",
        domysl: "Konsultacje socjalne · pomoc żywnościowa · wsparcie seniorów · informacje o świadczeniach rodzinnych",
      },
      { id: "data", etykieta: "Termin (opcjonalnie)", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godziny", typ: "time", domysl: "8:00–15:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Urząd Gminy / GOPS, {{gmina}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "GOPS {{gmina}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}} · {{email}}" },
    ],
    domyslnyMotyw: "ddk-gops-niebieski",
    dostep: "wszyscy",
    tagi: ["gops", "ddk", "pomoc"],
  },
  {
    id: "sponsor-podziekowanie",
    kategoria: "podziekowania",
    tytul: "Podziękowanie dla sponsora",
    opis: "Oficjalne podziękowanie firmie wspierającej imprezę wiejską.",
    layout: "podziekowanie",
    format: "a4",
    orientacja: "poziom",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Serdecznie dziękujemy" },
      { id: "tytul", etykieta: "Nazwa sponsora", typ: "text", domysl: "Firma …" },
      {
        id: "opis",
        etykieta: "Treść",
        typ: "textarea",
        domysl: "Za wsparcie finansowe i merytoryczne podczas imprezy w sołectwie {{wies}}.\nWasza pomoc pozwoliła zrealizować wspólne cele całej społeczności.",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "{{wies}}" },
      { id: "organizator", etykieta: "W imieniu", typ: "text", domysl: "{{organizator}}" },
      { id: "podpis1", etykieta: "Podpis", typ: "text", domysl: "Sołtys\n…" },
    ],
    domyslnyMotyw: "sponsor-zloto",
    dostep: "wszyscy",
    tagi: ["sponsor", "podziękowanie"],
  },
  {
    id: "sponsor-plakat",
    kategoria: "plakaty",
    tytul: "Plakat — patroni i sponsorzy imprezy",
    opis: "Logotypy patronów na plakacie festynu lub turnieju.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Patroni i sponsorzy" },
      { id: "tytul", etykieta: "Nazwa imprezy", typ: "text", domysl: "Festyn wiejski {{wies}}" },
      {
        id: "opis",
        etykieta: "Lista sponsorów",
        typ: "textarea",
        domysl: "★ Firma A — patronat honorowy\n★ Sklep B — nagrody\n★ Gospodarstwo C — catering\n★ Bank D — wsparcie finansowe",
      },
      { id: "data", etykieta: "Data imprezy", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "14:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "{{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · KGW · OSP" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "sponsor-zloto",
    dostep: "wszyscy",
    tagi: ["sponsor", "patronat", "festyn"],
  },
  {
    id: "biblioteka-spotkanie",
    kategoria: "zaproszenia",
    tytul: "Spotkanie w bibliotece wiejskiej",
    opis: "Czytanie, warsztaty, klub książki — dla dzieci i dorosłych.",
    layout: "karta-informacyjna",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Biblioteka zaprasza" },
      { id: "tytul", etykieta: "Tytuł spotkania", typ: "text", domysl: "Klub czytelniczy" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "Wspólne czytanie · dyskusja · gry słowne · herbata",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "16:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Biblioteka / świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Biblioteka Publiczna · Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "turkusowy-letni",
    dostep: "wszyscy",
    tagi: ["biblioteka", "szkoła", "czytanie"],
  },
];

export type GrupaWiejska =
  | "lowiectwo"
  | "parafia"
  | "seniorzy"
  | "sport"
  | "zespol"
  | "ddk"
  | "sponsor"
  | "rada"
  | "szkola"
  | "dyplomy"
  | "mix"
  | "wszystkie";

export const ETYKIETY_GRUP: Record<GrupaWiejska, string> = {
  wszystkie: "Wszystkie grupy",
  lowiectwo: "Myśliwi / koło łowieckie",
  parafia: "Parafia",
  seniorzy: "Klub seniora",
  sport: "Sport / LZS",
  zespol: "Zespół ludowy",
  ddk: "DDK / GOPS",
  sponsor: "Sponsorzy",
  rada: "Rada sołecka",
  szkola: "Szkoła / biblioteka",
  dyplomy: "Dyplomy i certyfikaty",
  mix: "Wspólne akcje",
};

export function tagiDoGrupy(tag: string[]): GrupaWiejska {
  if (tag.includes("łowiectwo") || tag.includes("myśliwi")) return "lowiectwo";
  if (tag.includes("parafia")) return "parafia";
  if (tag.includes("seniorzy")) return "seniorzy";
  if (tag.includes("sport") || tag.includes("LZS")) return "sport";
  if (tag.includes("zespół") || tag.includes("folklor")) return "zespol";
  if (tag.includes("gops") || tag.includes("ddk")) return "ddk";
  if (tag.includes("sponsor")) return "sponsor";
  if (tag.includes("rada")) return "rada";
  if (tag.includes("szkoła") || tag.includes("biblioteka")) return "szkola";
  if (tag.includes("dzieci") || tag.includes("Dzień Dziecka")) return "szkola";
  if (tag.includes("świetlica") || tag.includes("regulamin")) return "mix";
  if (tag.includes("fundusz") || tag.includes("zebranie") || tag.includes("informacja")) return "rada";
  if (tag.includes("mix")) return "mix";
  return "wszystkie";
}

export function zastosujPaczkeGrupy(
  uzupelnienia: Record<string, string>,
  kontekst: KontekstGrafiki,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(uzupelnienia)) {
    out[k] = uzupelnijPlaceholdery(v, kontekst);
  }
  return out;
}
