import type { SzablonGrafiki } from "./typy";

function polaDyplom(
  naglowek: string,
  opisDomysl: string,
  organizator: string,
  podpis1: string,
  podpis2 = "",
): SzablonGrafiki["pola"] {
  return [
    { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: naglowek },
    { id: "tytul", etykieta: "Imię i nazwisko", typ: "text", domysl: "…" },
    { id: "opis", etykieta: "Uzasadnienie / za co", typ: "textarea", domysl: opisDomysl },
    { id: "data", etykieta: "Data wręczenia", typ: "date", domysl: "" },
    { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "{{wies}}" },
    { id: "organizator", etykieta: "W imieniu / Nadaje", typ: "text", domysl: organizator },
    { id: "podpis1", etykieta: "Podpis 1 (funkcja + nazwisko)", typ: "text", domysl: podpis1 },
    { id: "podpis2", etykieta: "Podpis 2 (opcjonalnie)", typ: "text", domysl: podpis2 },
    { id: "podpis_cyfrowy", etykieta: "Podpis elektroniczny (imię i nazwisko)", typ: "text", domysl: "" },
  ];
}

/** Rozszerzona kolekcja dyplomów, certyfikatów i okolicznościowych zaproszeń. */
export const SZABLONY_DYPLOMY_ROZSZERZONE: SzablonGrafiki[] = [
  {
    id: "dyplom-parafia-ministrans",
    kategoria: "dyplomy",
    tytul: "Dyplom — ministranci / służba liturgiczna",
    opis: "Za służbę przy ołtarzu, ministrantów i lektorów.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za sumienne pełnienie obowiązków ministranta oraz zaangażowanie w życie liturgiczne parafii.",
      "Parafia pw. … · {{wies}}",
      "Proboszcz\n…",
      "Opiekun ministrantów\n…",
    ),
    domyslnyMotyw: "parafia-granat",
    dostep: "wszyscy",
    tagi: ["dyplom", "parafia", "ministranci"],
  },
  {
    id: "dyplom-parafia-schola",
    kategoria: "dyplomy",
    tytul: "Dyplom — schola / zespół liturgiczny",
    opis: "Podziękowanie dla członków scholi i zespołu muzycznego.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za wieloletnią służbę w scholi parafialnej oraz piękne prowadzenie śpiewu podczas Mszy św. i uroczystości.",
      "Parafia · Schola liturgiczna",
      "Proboszcz\n…",
      "Dyrygent scholi\n…",
    ),
    domyslnyMotyw: "parafia-granat",
    dostep: "wszyscy",
    tagi: ["dyplom", "parafia", "muzyka"],
  },
  {
    id: "dyplom-parafia-katecheta",
    kategoria: "dyplomy",
    tytul: "Dyplom — katecheta / animator duszpasterstwa",
    opis: "Za pracę z młodzieżą, dziećmi i dorosłymi w parafii.",
    layout: "dyplom-klasyczny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za wieloletnie zaangażowanie w katechezę parafialną, przygotowanie do sakramentów oraz troskę o wychowanie młodych w wierze.",
      "Parafia pw. … · {{wies}}",
      "Proboszcz\n…",
      "Przedstawiciel rady parafialnej\n…",
    ),
    domyslnyMotyw: "parafia-granat",
    dostep: "wszyscy",
    tagi: ["dyplom", "parafia", "katecheza"],
  },
  {
    id: "dyplom-osp-mlodziezowa",
    kategoria: "dyplomy",
    tytul: "Dyplom — młodzieżowa DMD / młodzi strażacy",
    opis: "Ukończenie szkolenia lub aktywność w młodzieżowej drużynie.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom ukończenia",
      "Za ukończenie szkolenia w Młodzieżowej Drużynie Pożarniczej oraz aktywny udział w ćwiczeniach i akcjach OSP {{wies}}.",
      "OSP {{wies}} · Młodzieżowa DMD",
      "Opiekun młodzieżowej DMD\n…",
      "Naczelnik OSP\n…",
    ),
    domyslnyMotyw: "osp-czerwony",
    dostep: "osp",
    tagi: ["dyplom", "OSP", "młodzież"],
  },
  {
    id: "dyplom-osp-weteran",
    kategoria: "dyplomy",
    tytul: "Dyplom — weteran OSP (wieloletnia służba)",
    opis: "Jubileusz 5, 10, 25 lub 50 lat służby w straży pożarnej.",
    layout: "dyplom-medal",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za wieloletnią, bezinteresowną służbę w Ochotniczej Straży Pożarnej oraz wkład w bezpieczeństwo mieszkańców sołectwa {{wies}}.",
      "OSP {{wies}}",
      "Naczelnik OSP\n…",
      "Sołtys\n…",
    ),
    domyslnyMotyw: "osp-czerwony",
    dostep: "osp",
    tagi: ["dyplom", "OSP", "jubileusz"],
  },
  {
    id: "dyplom-lowca-roku",
    kategoria: "dyplomy",
    tytul: "Dyplom — Łowca Roku",
    opis: "Wyróżnienie w konkursie lub uroczystości koła łowieckiego.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Łowca Roku",
      "Za wzorową postawę łowiecką, aktywność w pracach koła oraz dbałość o etykę i tradycje myślistwa.",
      "Koło Łowieckie „…\" · {{wies}}",
      "Prezes koła\n…",
      "Zołnierz łowiecki\n…",
    ),
    domyslnyMotyw: "lowiecki-lesny",
    dostep: "wszyscy",
    tagi: ["dyplom", "łowiectwo"],
  },
  {
    id: "dyplom-lowiecki-egzamin",
    kategoria: "dyplomy",
    tytul: "Certyfikat — egzamin / szkolenie łowieckie",
    opis: "Ukończenie kursu, egzaminu na patent lub szkolenia BHP.",
    layout: "dyplom-klasyczny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Certyfikat ukończenia",
      "Za pomyślne ukończenie szkolenia / egzaminu łowieckiego oraz wykazanie się wiedzą z zakresu przepisów i etyki myśliwskiej.",
      "Koło Łowieckie „…\"",
      "Instruktor / egzaminator\n…",
      "Prezes koła\n…",
    ),
    domyslnyMotyw: "lowiecki-lesny",
    dostep: "wszyscy",
    tagi: ["dyplom", "łowiectwo", "certyfikat", "szkolenie"],
  },
  {
    id: "dyplom-sport-mistrz",
    kategoria: "dyplomy",
    tytul: "Dyplom — mistrz turnieju / najlepszy zawodnik",
    opis: "Po turnieju piłkarskim, siatkarskim lub crossie LZS.",
    layout: "dyplom-medal",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom Mistrza",
      "Za zdobycie I miejsca w turnieju sportowym o Puchar Sołtysa {{wies}} oraz wzorową postawę sportową.",
      "LZS / Klub sportowy {{wies}}",
      "Prezes klubu\n…",
      "Sołtys\n…",
    ),
    domyslnyMotyw: "sport-lzs",
    dostep: "wszyscy",
    tagi: ["dyplom", "sport", "turniej"],
  },
  {
    id: "dyplom-sport-fair-play",
    kategoria: "dyplomy",
    tytul: "Dyplom Fair Play",
    opis: "Wyróżnienie za fair play, współpracę i postawę fair play na boisku.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Nagroda Fair Play",
      "Za wzorową postawę fair play, fair play w stosunku do rywali i promowanie wartości sportowych wśród młodzieży.",
      "Organizator turnieju · {{wies}}",
      "Sędzia główny\n…",
      "Prezes LZS\n…",
    ),
    domyslnyMotyw: "sport-lzs",
    dostep: "wszyscy",
    tagi: ["dyplom", "sport", "fair play"],
  },
  {
    id: "dyplom-wolontariusz",
    kategoria: "dyplomy",
    tytul: "Dyplom wolontariusza",
    opis: "Za pomoc przy festynie, zbiórce, akcji charytatywnej lub remoncie.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom wolontariusza",
      "Za nieocenioną, bezinteresowną pomoc przy organizacji wydarzenia oraz zaangażowanie na rzecz dobra wspólnoty sołectwa {{wies}}.",
      "Sołectwo {{wies}}",
      "Sołtys\n…",
      "Koordynator wolontariatu\n…",
    ),
    domyslnyMotyw: "zielony-wies",
    dostep: "wszyscy",
    tagi: ["dyplom", "wolontariat"],
  },
  {
    id: "dyplom-zasluzony-mieszkaniec",
    kategoria: "dyplomy",
    tytul: "Dyplom — zasłużony mieszkaniec wsi",
    opis: "Honorowe wyróżnienie od sołtysa i rady sołeckiej.",
    layout: "dyplom-pergamin",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom Zasłużonego Mieszkańca",
      "Za wieloletnie zaangażowanie w życie społeczne sołectwa {{wies}}, wspieranie inicjatyw lokalnych oraz wzorową postawę obywatelską.",
      "Rada Sołecka · Sołectwo {{wies}}",
      "Sołtys\n…",
      "Przewodniczący Rady Sołeckiej\n…",
    ),
    domyslnyMotyw: "klasyczny-bialy",
    dostep: "soltys",
    tagi: ["dyplom", "sołectwo", "honor"],
  },
  {
    id: "dyplom-senior-aktywnosc",
    kategoria: "dyplomy",
    tytul: "Dyplom — aktywny senior",
    opis: "Za udział w klubie seniora, wycieczkach i warsztatach.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za aktywny udział w działalności Klubu Seniora, promowanie integracji międzypokoleniowej oraz wspieranie inicjatyw lokalnych.",
      "Klub Seniora · {{wies}}",
      "Przewodniczący klubu\n…",
      "Koordynator GOPS\n…",
    ),
    domyslnyMotyw: "seniorzy-cieply",
    dostep: "wszyscy",
    tagi: ["dyplom", "seniorzy"],
  },
  {
    id: "dyplom-rodzic-wspierajacy",
    kategoria: "dyplomy",
    tytul: "Dyplom — wspierający rodzic / opiekun",
    opis: "Za pomoc szkole, świetlicy, KGW lub wydarzeniom dziecięcym.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom podziękowania",
      "Za wsparcie organizacji wydarzeń szkolnych i lokalnych, pomoc w przygotowaniu imprez oraz troskę o dobro dzieci sołectwa {{wies}}.",
      "Szkoła / Sołectwo {{wies}}",
      "Dyrektor szkoły\n…",
      "Sołtys\n…",
    ),
    domyslnyMotyw: "turkusowy-letni",
    dostep: "wszyscy",
    tagi: ["dyplom", "szkoła", "rodzice"],
  },
  {
    id: "dyplom-patriotyczny",
    kategoria: "dyplomy",
    tytul: "Dyplom — konkurs patriotyczny",
    opis: "Święto Niepodległości, recytacja, plakat historyczny.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za udział w konkursie patriotycznym z okazji Narodowego Święta Niepodległości oraz promowanie historii i tradycji lokalnej.",
      "Sołectwo {{wies}} · Szkoła Podstawowa",
      "Sołtys\n…",
      "Nauczyciel prowadzący\n…",
    ),
    domyslnyMotyw: "elegancki-zloty",
    dostep: "wszyscy",
    tagi: ["dyplom", "patriotyzm", "konkurs", "szkoła"],
  },
  {
    id: "certyfikat-szkolenie-bezpieczenstwo",
    kategoria: "dyplomy",
    tytul: "Certyfikat — szkolenie BHP / pierwsza pomoc",
    opis: "Po szkoleniu strażackim, pierwszej pomocy lub BHP dla mieszkańców.",
    layout: "dyplom-klasyczny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Certyfikat ukończenia szkolenia",
      "Za ukończenie szkolenia z zakresu bezpieczeństwa, pierwszej pomocy przedmedycznej oraz zasad postępowania w sytuacjach zagrożenia.",
      "OSP {{wies}} / Sołectwo {{wies}}",
      "Instruktor szkolenia\n…",
      "Naczelnik OSP\n…",
    ),
    domyslnyMotyw: "osp-czerwony",
    dostep: "wszyscy",
    tagi: ["certyfikat", "szkolenie", "BHP", "OSP"],
  },
  {
    id: "dyplom-kgw-kiermasz",
    kategoria: "dyplomy",
    tytul: "Dyplom — kiermasz / stoisko KGW",
    opis: "Za wkład w kiermasz, jarmark lub stoisko na festynie.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za wkład w organizację kiermaszu KGW, przygotowanie wyrobów rękodzielniczych i kulinarnych oraz promocję tradycji wiejskich.",
      "KGW {{wies}}",
      "Przewodnicząca KGW\n…",
      "Sołtys\n…",
    ),
    domyslnyMotyw: "kgw-rozowy",
    dostep: "kgw",
    tagi: ["dyplom", "KGW", "kiermasz"],
  },
  {
    id: "dyplom-zespol-folklor",
    kategoria: "dyplomy",
    tytul: "Dyplom — zespół ludowy / folklor",
    opis: "Za występ, wieloletnią działalność lub udział w przeglądzie.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za promowanie kultury ludowej, występy podczas uroczystości wiejskich oraz utrwalanie tradycji tańca i muzyki regionu.",
      "Zespół Ludowy „…\" · {{wies}}",
      "Kierownik zespołu\n…",
      "Sołtys\n…",
    ),
    domyslnyMotyw: "folklor-kolorowy",
    dostep: "wszyscy",
    tagi: ["dyplom", "folklor", "zespół"],
  },
  {
    id: "dyplom-komunia-gratulacje",
    kategoria: "dyplomy",
    tytul: "Dyplom — Pierwsza Komunia Święta",
    opis: "Pamiątkowy dyplom dla dziecka po Komunii Świętej.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Pamiątka Pierwszej Komunii Świętej",
      "Za uroczyste przyjęcie sakramentu Eucharystii oraz aktywny udział w przygotowaniu do Komunii Świętej.",
      "Parafia pw. … · {{wies}}",
      "Proboszcz\n…",
      "Katecheta\n…",
    ),
    domyslnyMotyw: "parafia-granat",
    dostep: "wszyscy",
    tagi: ["dyplom", "komunia", "parafia"],
  },
  {
    id: "dyplom-jubileusz-malzenski",
    kategoria: "dyplomy",
    tytul: "Dyplom — jubileusz małżeński",
    opis: "50, 40 lub 25 lat małżeństwa — od parafii lub sołectwa.",
    layout: "dyplom-pergamin",
    format: "a4",
    orientacja: "poziom",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Jubileusz małżeński" },
      { id: "tytul", etykieta: "Małżonkowie (imię i nazwisko)", typ: "text", domysl: "…" },
      {
        id: "opis",
        etykieta: "Treść / ile lat",
        typ: "textarea",
        domysl: "Z okazji 50. rocznicy zawarcia sakramentu małżeństwa składamy wyrazy uznania za wzorową postawę rodzinną i wkład w życie wspólnoty parafialnej.",
      },
      { id: "data", etykieta: "Data uroczystości", typ: "date", domysl: "" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "{{wies}}" },
      { id: "organizator", etykieta: "W imieniu", typ: "text", domysl: "Parafia · Sołectwo {{wies}}" },
      { id: "podpis1", etykieta: "Podpis 1", typ: "text", domysl: "Proboszcz\n…" },
      { id: "podpis2", etykieta: "Podpis 2", typ: "text", domysl: "Sołtys\n…" },
      { id: "podpis_cyfrowy", etykieta: "Podpis elektroniczny", typ: "text", domysl: "" },
    ],
    domyslnyMotyw: "elegancki-zloty",
    dostep: "wszyscy",
    tagi: ["dyplom", "jubileusz", "parafia"],
  },
  {
    id: "zaproszenie-komunia",
    kategoria: "zaproszenia",
    tytul: "Zaproszenie — Pierwsza Komunia Święta",
    opis: "Zaproszenie na uroczystość komunijną i wspólne świętowanie.",
    layout: "zaproszenie-eleganckie",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Serdecznie zapraszamy" },
      { id: "tytul", etykieta: "Imię dziecka / okazja", typ: "text", domysl: "Na Pierwszą Komunię Świętą …" },
      {
        id: "opis",
        etykieta: "Szczegóły",
        typ: "textarea",
        domysl: "Msza św. o godz. … w kościele parafialnym.\nPo uroczystości zapraszamy na wspólne świętowanie.",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina Mszy", typ: "time", domysl: "10:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Kościół parafialny, {{wies}}" },
      { id: "organizator", etykieta: "Zapraszają", typ: "text", domysl: "Rodzina …" },
      { id: "kontakt", etykieta: "Kontakt / RSVP", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "parafia-granat",
    dostep: "wszyscy",
    tagi: ["zaproszenie", "komunia", "parafia"],
  },
  {
    id: "zaproszenie-chrzest",
    kategoria: "zaproszenia",
    tytul: "Zaproszenie na chrzest święty",
    opis: "Uroczystość chrztu i spotkanie po ceremonii.",
    layout: "zaproszenie-eleganckie",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Z radością zapraszamy" },
      { id: "tytul", etykieta: "Imię dziecka", typ: "text", domysl: "Na chrzest święty …" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "Ceremonia chrztu w kościele parafialnym.\nPo uroczystości wspólne spotkanie rodzinne.",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "12:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Kościół parafialny, {{wies}}" },
      { id: "organizator", etykieta: "Rodzice / chrzestni", typ: "text", domysl: "…" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "parafia-granat",
    dostep: "wszyscy",
    tagi: ["zaproszenie", "chrzest", "parafia"],
  },
  {
    id: "plakat-dzien-dziecka",
    kategoria: "plakaty",
    tytul: "Plakat — Dzień Dziecka",
    opis: "Piknik, zabawy na boisku lub festyn dla dzieci ze wsi.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Wesołego Dnia Dziecka!" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Piknik rodzinny w {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "• Gry i zabawy na świeżym powietrzu\n• Animacje dla najmłodszych\n• Słodki poczęstunek\n• Konkursy z nagrodami",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "15:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Boisko / plac zabaw, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · Szkoła · KGW" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "turkusowy-letni",
    dostep: "wszyscy",
    tagi: ["plakat", "Dzień Dziecka", "dzieci"],
  },
  {
    id: "plakat-wigilia-wies",
    kategoria: "plakaty",
    tytul: "Plakat — Wigilia wiejska / opłatek",
    opis: "Wspólna Wigilia mieszkańców, opłatek w świetlicy.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Spotkajmy się przed Świętami" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Wigilia mieszkańców {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "Wspólne dzielenie się opłatkiem · kolędy · poczęstunek · spotkanie sąsiedzkie",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "17:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Świetlica wiejska, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · Parafia · KGW" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "elegancki-zloty",
    dostep: "wszyscy",
    tagi: ["plakat", "wigilia", "święta", "sezon"],
  },
  {
    id: "dyplom-fundator-wsi",
    kategoria: "dyplomy",
    tytul: "Dyplom — fundator / partner wsi",
    opis: "Dla firmy, instytucji lub osoby wspierającej inicjatywy sołeckie.",
    layout: "dyplom-pergamin",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Dyplom uznania",
      "Za wsparcie finansowe lub rzeczowe inicjatyw sołectwa {{wies}} oraz zaangażowanie na rzecz dobra wspólnoty lokalnej.",
      "Sołectwo {{wies}} · Rada Sołecka",
      "Sołtys\n…",
      "Przewodniczący Rady Sołeckiej\n…",
    ),
    domyslnyMotyw: "elegancki-zloty",
    dostep: "soltys",
    tagi: ["dyplom", "sponsor", "fundator"],
  },
  {
    id: "certyfikat-partner-imprezy",
    kategoria: "dyplomy",
    tytul: "Certyfikat — partner / patron imprezy",
    opis: "Podziękowanie dla sponsora festynu, dożynków lub akcji charytatywnej.",
    layout: "dyplom-medal",
    format: "a4",
    orientacja: "poziom",
    pola: polaDyplom(
      "Certyfikat Partnera",
      "Za objęcie patronatem / wsparciem imprezy oraz promowanie dobrego imienia sołectwa {{wies}}.",
      "Organizatorzy imprezy · {{wies}}",
      "Sołtys\n…",
      "Koordynator festynu\n…",
    ),
    domyslnyMotyw: "sponsor-zloto",
    dostep: "wszyscy",
    tagi: ["dyplom", "sponsor", "festyn"],
  },
  {
    id: "plakat-kronika-wsi",
    kategoria: "plakaty",
    tytul: "Plakat — kronika wsi / spotkanie wspominkowe",
    opis: "Zaproszenie na spotkanie przy kawie, wystawę zdjęć lub kronikę oralną.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Pamiętamy i opowiadamy" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Kronika wsi {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "Wspólne wspomnienia · zdjęcia archiwalne · nagrania · poczęstunek",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "17:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · Klub Seniora" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "seniorzy-cieply",
    dostep: "wszyscy",
    tagi: ["plakat", "historia", "seniorzy"],
  },
];
