import type { SzablonGrafiki } from "./typy";

/** Szablony sezonowe — Mikołajki, Dzień Kobiet, Dożynki, Wielkanoc */
export const SZABLONY_SEZONOWE: SzablonGrafiki[] = [
  {
    id: "sezon-mikolajki",
    kategoria: "zaproszenia",
    tytul: "Mikołajki w świetlicy",
    opis: "Zaproszenie na spotkanie mikołajkowe dla dzieci z wsi.",
    layout: "zaproszenie-rustykalne",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Ho ho ho! Zapraszamy na Mikołajki" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Mikołajki w {{wies}}" },
      { id: "opis", etykieta: "Program", typ: "textarea", domysl: "W programie: kolędy, rozdawanie prezentów, poczęstunek i zabawy dla najmłodszych." },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "16:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "osp-czerwony",
    dostep: "wszyscy",
    tagi: ["sezon", "mikołajki", "święta"],
  },
  {
    id: "sezon-dzien-kobiet",
    kategoria: "zaproszenia",
    tytul: "Dzień Kobiet — spotkanie KGW",
    opis: "Zaproszenie na spotkanie z okazji 8 marca.",
    layout: "zaproszenie-nowoczesne",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Z okazji Dnia Kobiet" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Spotkanie kobiet z {{wies}}" },
      { id: "opis", etykieta: "Program", typ: "textarea", domysl: "Wspólne świętowanie, koncert, kwiaty i dobre rozmowy przy kawie." },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "17:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "{{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "KGW {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "kgw-rozowy",
    dostep: "wszyscy",
    tagi: ["sezon", "8 marca", "KGW"],
  },
  {
    id: "sezon-dozynki",
    kategoria: "plakaty",
    tytul: "Dożynki / festyn dożynkowy",
    opis: "Plakat na dożynki z programem i datą.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "{{wies}} świętuje!" },
      { id: "tytul", etykieta: "Nazwa", typ: "text", domysl: "Dożynki 2026" },
      { id: "opis", etykieta: "Program", typ: "textarea", domysl: "• Korowód dożynkowy\n• Występy zespołów\n• Kiermasz KGW\n• Poczęstunek chlebem i solą" },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "14:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Plac przy świetlicy, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "zielony-wies",
    dostep: "wszyscy",
    tagi: ["sezon", "dożynki", "festyn"],
  },
  {
    id: "sezon-wielkanoc",
    kategoria: "zaproszenia",
    tytul: "Spotkanie wielkanocne",
    opis: "Zaproszenie na śniadanie wielkanocne lub kiermasz ozdób.",
    layout: "zaproszenie-eleganckie",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Wesołych Świąt!" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Wielkanocne spotkanie w {{wies}}" },
      { id: "opis", etykieta: "Opis", typ: "textarea", domysl: "Wspólne śniadanie, dzielenie się jajkiem i kiermasz palm wielkanocnych." },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "11:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "turkusowy-letni",
    dostep: "wszyscy",
    tagi: ["sezon", "wielkanoc"],
  },
  {
    id: "sezon-sylwester",
    kategoria: "plakaty",
    tytul: "Sylwester w świetlicy",
    opis: "Plakat na zabawę sylwestrową dla mieszkańców.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Powitajmy Nowy Rok razem!" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Sylwester w {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "• Muzyka na żywo\n• Konkursy i zabawy\n• Toast o północy\n• Poczęstunek",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "20:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "fioletowy-festyn",
    dostep: "wszyscy",
    tagi: ["sezon", "sylwester", "nowy rok"],
  },
  {
    id: "sezon-pozegnanie-lata",
    kategoria: "plakaty",
    tytul: "Pożegnanie lata",
    opis: "Ognisko, grill, integracja — plakat na imprezę letnią.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Lato minęło — świętujmy razem!" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Pożegnanie lata w {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "Ognisko · kiełbaski z grilla · muzyka · zabawy dla dzieci",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "18:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Plac / boisko, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · OSP" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "turkusowy-letni",
    dostep: "wszyscy",
    tagi: ["sezon", "lato", "ognisko"],
  },
  {
    id: "sezon-dni-seniora",
    kategoria: "zaproszenia",
    tytul: "Dni Seniora — spotkanie",
    opis: "Zaproszenie na uroczystość z okazji Międzynarodowego Dnia Osób Starszych.",
    layout: "zaproszenie-eleganckie",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Z okazji Dni Seniora" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Spotkanie seniorów {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "Koncert · poczęstunek · rozmowy przy kawie · upominki",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "11:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Klub Seniora · GOPS {{gmina}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "seniorzy-cieply",
    dostep: "wszyscy",
    tagi: ["sezon", "seniorzy", "Dni Seniora"],
  },
];

export type PaczkaSezonowa = {
  id: string;
  nazwa: string;
  opis: string;
  szablonId: string;
  emoji: string;
  motywId?: string;
  tytulProjektu?: string;
  badge?: string;
};

export const PACZKI_SEZONOWE: PaczkaSezonowa[] = [
  { id: "mikolajki", nazwa: "Mikołajki", opis: "Spotkanie dla dzieci", szablonId: "sezon-mikolajki", emoji: "🎅", motywId: "osp-czerwony", tytulProjektu: "Mikołajki w świetlicy", badge: "Grudzień" },
  { id: "dzien-kobiet", nazwa: "Dzień Kobiet", opis: "KGW, 8 marca", szablonId: "sezon-dzien-kobiet", emoji: "💐", motywId: "kgw-rozowy", tytulProjektu: "Spotkanie KGW — 8 marca" },
  { id: "dozynki", nazwa: "Dożynki", opis: "Plakat festynu", szablonId: "sezon-dozynki", emoji: "🌾", motywId: "zielony-wies", tytulProjektu: "Dożynki", badge: "WOW" },
  { id: "wielkanoc", nazwa: "Wielkanoc", opis: "Spotkanie świąteczne", szablonId: "sezon-wielkanoc", emoji: "🐣", motywId: "turkusowy-letni", tytulProjektu: "Spotkanie wielkanocne" },
  { id: "sylwester", nazwa: "Sylwester", opis: "Zabawa w świetlicy", szablonId: "sezon-sylwester", emoji: "🎆", motywId: "fioletowy-festyn", tytulProjektu: "Sylwester" },
  { id: "pozegnanie-lata", nazwa: "Pożegnanie lata", opis: "Ognisko i grill", szablonId: "sezon-pozegnanie-lata", emoji: "🔥", motywId: "turkusowy-letni", tytulProjektu: "Pożegnanie lata" },
  { id: "dni-seniora", nazwa: "Dni Seniora", opis: "Spotkanie klubu", szablonId: "sezon-dni-seniora", emoji: "👴", motywId: "seniorzy-cieply", tytulProjektu: "Dni Seniora" },
  { id: "dzien-dziecka", nazwa: "Dzień Dziecka", opis: "Kolorowy plakat z animacjami", szablonId: "plakat-dzien-dziecka-kolorowy", emoji: "🎈", motywId: "dzieci-radosny", tytulProjektu: "Dzień Dziecka", badge: "1 czerwca" },
  { id: "swietlica-zajecia", nazwa: "Zajęcia w świetlicy", opis: "Harmonogram tygodniowy", szablonId: "plakat-zajecia-swietlicy", emoji: "🏠", motywId: "swietlica-ciepla", tytulProjektu: "Harmonogram świetlicy" },
  { id: "11-listopada", nazwa: "11 listopada", opis: "Uroczystość patriotyczna", szablonId: "plakat-11-listopada", emoji: "🇵🇱", motywId: "patriotyczny-granat", tytulProjektu: "Święto Niepodległości", badge: "Listopad" },
  { id: "zebranie-tablica", nazwa: "Zebranie wiejskie", opis: "Ogłoszenie na tablicę", szablonId: "plakat-zebranie-tablica", emoji: "📋", motywId: "tablica-czerwony", tytulProjektu: "Zebranie sołectwa" },
];
