import type { SzablonGrafiki } from "./typy";

const polaPlakatOgloszenie = [
  { id: "naglowek", etykieta: "Etykieta górna", typ: "text" as const, domysl: "OGŁOSZENIE · SOŁECTWO" },
  { id: "tytul", etykieta: "Tytuł", typ: "text" as const, domysl: "Zebranie mieszkańców {{wies}}" },
  {
    id: "opis",
    etykieta: "Treść ogłoszenia",
    typ: "textarea" as const,
    domysl:
      "Zapraszamy wszystkich mieszkańców na zebranie wiejskie.\n\nPorządek obrad:\n1. Sprawy bieżące\n2. Fundusz sołecki\n3. Sprawy różne",
  },
  { id: "data", etykieta: "Data", typ: "date" as const, domysl: "" },
  { id: "godzina", etykieta: "Godzina", typ: "time" as const, domysl: "18:00" },
  { id: "miejsce", etykieta: "Miejsce", typ: "text" as const, domysl: "Świetlica, {{wies}}" },
  { id: "organizator", etykieta: "W imieniu", typ: "text" as const, domysl: "Sołtys sołectwa {{wies}}" },
  { id: "kontakt", etykieta: "Kontakt", typ: "text" as const, domysl: "{{telefon}}" },
];

/** Plakaty informacyjne, tablica ogłoszeń, fundusz, kiermasze, święta państwowe. */
export const SZABLONY_SOLECTWO_ROZSZERZONE: SzablonGrafiki[] = [
  {
    id: "plakat-zebranie-tablica",
    kategoria: "plakaty",
    tytul: "Plakat — zebranie wiejskie (tablica)",
    opis: "Wyraźne ogłoszenie na tablicę informacyjną lub do sklepu.",
    layout: "plakat-ogloszenie",
    format: "a4",
    orientacja: "pion",
    pola: polaPlakatOgloszenie,
    domyslnyMotyw: "tablica-czerwony",
    dostep: "soltys",
    tagi: ["plakat", "zebranie", "informacja", "wow"],
  },
  {
    id: "karta-kontakt-solectwa",
    kategoria: "karty",
    tytul: "Karta — kontakt do sołectwa",
    opis: "Telefony, godziny, adres — do powieszenia w sklepie lub urzędzie.",
    layout: "karta-informacyjna",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Kontakt — sołectwo {{wies}}" },
      { id: "tytul", etykieta: "Podtytuł", typ: "text", domysl: "Gmina {{gmina}}" },
      {
        id: "opis",
        etykieta: "Dane kontaktowe",
        typ: "textarea",
        domysl:
          "Sołtys: … — tel. …\nPrzewodniczący Rady Sołeckiej: …\nŚwietlica: …\nOSP: …\n\nGodziny przyjmowania interesantów: …",
      },
      { id: "kontakt", etykieta: "Strona / e-mail", typ: "text", domysl: "naszawies.pl" },
      { id: "organizator", etykieta: "Stopka", typ: "text", domysl: "Rada Sołecka {{wies}}" },
    ],
    domyslnyMotyw: "zielony-wies",
    dostep: "soltys",
    tagi: ["informacja", "kontakt", "rada"],
  },
  {
    id: "plakat-fundusz-sołecki",
    kategoria: "plakaty",
    tytul: "Plakat — fundusz sołecki (plan zadań)",
    opis: "Informacja o planowanych inwestycjach z funduszu sołeckiego.",
    layout: "plakat-swietlica",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Fundusz sołecki {{wies}}" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Plan zadań na rok …" },
      {
        id: "opis",
        etykieta: "Zadania / kwoty",
        typ: "textarea",
        domysl:
          "1. Remont podłogi w świetlicy — 8 000 zł\n2. Plac zabaw — 5 000 zł\n3. Oświetlenie boiska — 3 000 zł\n\nŹródło: uchwała Rady Gminy · głosowanie na zebraniu sołeckim",
      },
      { id: "data", etykieta: "Data zebrania / publikacji", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Tablica ogłoszeń, {{wies}}" },
      { id: "organizator", etykieta: "Publikuje", typ: "text", domysl: "Rada Sołecka {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "Sołtys — tel. …" },
    ],
    domyslnyMotyw: "wow-premium",
    dostep: "soltys",
    tagi: ["informacja", "fundusz", "rada", "wow"],
  },
  {
    id: "plakat-kiermasz-jesien",
    kategoria: "plakaty",
    tytul: "Plakat — kiermasz jesienny / KGW",
    opis: "Jarmark wyrobów domowych, ciasta, przetworów i rękodzieła.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Smaki i rękodzieło z naszej wsi" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Kiermasz jesienny KGW {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "• Stoiska z wypiekami i przetworami\n• Rękodzieło i ozdoby\n• Koncert zespołu regionalnego\n• Ciepłe napoje",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "10:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Plac przy świetlicy, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "KGW {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "kgw-rozowy",
    dostep: "wszyscy",
    tagi: ["plakat", "festyn", "KGW", "kiermasz"],
  },
  {
    id: "plakat-zbiorka-odpadow",
    kategoria: "plakaty",
    tytul: "Plakat — zbiórka odpadów / elektrośmieci",
    opis: "Harmonogram wywozu gabarytów, puszek, baterii lub sprzętu RTV.",
    layout: "plakat-ogloszenie",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Etykieta", typ: "text", domysl: "UWAGA MIESZKAŃCY" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Zbiórka gabarytów i elektrośmieci" },
      {
        id: "opis",
        etykieta: "Szczegóły",
        typ: "textarea",
        domysl:
          "W wyznaczonym terminie można wystawić:\n• meble, materace, dywany\n• sprzęt RTV i AGD\n• baterie i puszki (osobny kontener)\n\nProsimy o wystawienie w wyznaczone miejsce do godz. …",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina zakończenia", typ: "time", domysl: "12:00" },
      { id: "miejsce", etykieta: "Miejsce zbiórki", typ: "text", domysl: "Parking przy świetlicy, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · Gmina {{gmina}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "Urząd gminy / sołtys" },
    ],
    domyslnyMotyw: "tablica-czerwony",
    dostep: "soltys",
    tagi: ["plakat", "informacja", "środowisko"],
  },
  {
    id: "plakat-11-listopada",
    kategoria: "plakaty",
    tytul: "Plakat — 11 listopada / uroczystość",
    opis: "Obchody Narodowego Święta Niepodległości, msza, modlitwa, koncert.",
    layout: "plakat",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "11 listopada · Święto Niepodległości" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Uroczystość w {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "• Msza św. w intencji Ojczyzny\n• Złożenie kwiatów przy obelisku\n• Koncert pieśni patriotycznych\n• Spotkanie przy kawie w świetlicy",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "10:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Kościół / pomnik, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · Parafia · OSP" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "patriotyczny-granat",
    dostep: "wszyscy",
    tagi: ["plakat", "sezon", "patriotyzm", "wow"],
  },
  {
    id: "plakat-remont-inwestycja",
    kategoria: "plakaty",
    tytul: "Plakat — remont / inwestycja w toku",
    opis: "Informacja o robotach drogowych, remoncie mostu lub budowie chodnika.",
    layout: "plakat-ogloszenie",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Etykieta", typ: "text", domysl: "INFORMACJA DLA MIESZKAŃCÓW" },
      { id: "tytul", etykieta: "Tytuł inwestycji", typ: "text", domysl: "Remont drogi w {{wies}}" },
      {
        id: "opis",
        etykieta: "Zakres / utrudnienia",
        typ: "textarea",
        domysl:
          "W terminie … prowadzone są roboty drogowe na odcinku …\n\nProsimy o ostrożną jazdę i korzystanie z objazdu.\nPrzepraszamy za utrudnienia.",
      },
      { id: "data", etykieta: "Termin od", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina (opcjonalnie)", typ: "time", domysl: "" },
      { id: "miejsce", etykieta: "Lokalizacja", typ: "text", domysl: "ul. …, {{wies}}" },
      { id: "organizator", etykieta: "Wykonawca / zleceniodawca", typ: "text", domysl: "Gmina {{gmina}} · Sołectwo {{wies}}" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "Sołtys — tel. …" },
    ],
    domyslnyMotyw: "nowoczesny-granat",
    dostep: "soltys",
    tagi: ["plakat", "informacja", "inwestycja"],
  },
  {
    id: "karta-program-festynu",
    kategoria: "karty",
    tytul: "Karta — program festynu / dożynków",
    opis: "Rozkład godzinowy wydarzenia do rozdania lub powieszenia przy scenie.",
    layout: "karta-regulamin",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Program imprezy" },
      { id: "tytul", etykieta: "Nazwa wydarzenia", typ: "text", domysl: "Festyn dożynkowy {{wies}}" },
      {
        id: "opis",
        etykieta: "Punkty programu",
        typ: "textarea",
        domysl:
          "14:00 — Otwarcie, powitanie gości\n14:30 — Korowód dożynkowy\n15:00 — Występy zespołów\n16:00 — Kiermasz KGW\n17:00 — Wręczenie nagród\n18:00 — Zabawa do białego rana",
      },
      { id: "kontakt", etykieta: "Organizator / kontakt", typ: "text", domysl: "Sołectwo {{wies}} — tel. …" },
      { id: "organizator", etykieta: "Stopka", typ: "text", domysl: "{{wies}} · {{gmina}}" },
    ],
    domyslnyMotyw: "wow-festyn",
    dostep: "wszyscy",
    tagi: ["festyn", "dożynki", "program", "wow"],
  },
  {
    id: "plakat-piknik-rodzinny",
    kategoria: "plakaty",
    tytul: "Plakat — piknik rodzinny / integracja",
    opis: "Spotkanie sąsiedzkie, grill, gry na trawie — nie tylko dla dzieci.",
    layout: "plakat-dzieci",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text", domysl: "Spotkajmy się na trawie!" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Piknik rodzinny {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "• Gry integracyjne dla całych rodzin\n• Stoisko z grillowymi przysmakami\n• Muzyka na żywo\n• Konkursy z nagrodami",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "15:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Boisko / park, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · Rada Sołecka" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "wow-energia",
    dostep: "wszyscy",
    tagi: ["plakat", "festyn", "integracja", "dzieci"],
  },
  {
    id: "zaproszenie-ognisko-jesien",
    kategoria: "zaproszenia",
    tytul: "Zaproszenie — ognisko jesienne",
    opis: "Pożegnanie sezonu, kiełbasa, pieśni przy ognisku.",
    layout: "zaproszenie-rustykalne",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text", domysl: "Zapraszamy na ognisko" },
      { id: "tytul", etykieta: "Tytuł", typ: "text", domysl: "Jesienne ognisko w {{wies}}" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea",
        domysl: "Wspólne pieczenie kiełbasy, herbata z imbirem, pieśni przy ognisku i dobra atmosfera.",
      },
      { id: "data", etykieta: "Data", typ: "date", domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time", domysl: "18:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text", domysl: "Polana przy świetlicy, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text", domysl: "Sołectwo {{wies}} · OSP" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text", domysl: "tel. …" },
    ],
    domyslnyMotyw: "lowiecki-lesny",
    dostep: "wszyscy",
    tagi: ["zaproszenie", "sezon", "ognisko", "jesień"],
  },
];
