import type { SzablonGrafiki } from "./typy";

const polaPlakatDzieci = [
  { id: "naglowek", etykieta: "Hasło", typ: "text" as const, domysl: "Wesołego Dnia Dziecka!" },
  { id: "tytul", etykieta: "Tytuł", typ: "text" as const, domysl: "Piknik dla dzieci w {{wies}}" },
  {
    id: "opis",
    etykieta: "Program / atrakcje",
    typ: "textarea" as const,
    domysl:
      "🎈 Animacje i zabawy ruchowe\n🎨 Kącik plastyczny\n🍦 Słodki poczęstunek\n🏆 Konkursy z nagrodami\n🎵 Mini disco",
  },
  { id: "data", etykieta: "Data", typ: "date" as const, domysl: "" },
  { id: "godzina", etykieta: "Godzina", typ: "time" as const, domysl: "15:00" },
  { id: "miejsce", etykieta: "Miejsce", typ: "text" as const, domysl: "Świetlica wiejska, {{wies}}" },
  { id: "organizator", etykieta: "Organizator", typ: "text" as const, domysl: "Sołectwo {{wies}} · Szkoła · KGW" },
  { id: "kontakt", etykieta: "Kontakt", typ: "text" as const, domysl: "{{telefon}}" },
];

const polaKartaRegulamin = [
  { id: "naglowek", etykieta: "Nagłówek", typ: "text" as const, domysl: "Regulamin świetlicy wiejskiej" },
  { id: "tytul", etykieta: "Podtytuł / obiekt", typ: "text" as const, domysl: "Świetlica — {{wies}}" },
  {
    id: "opis",
    etykieta: "Punkty regulaminu",
    typ: "textarea" as const,
    domysl:
      "1. Korzystanie ze świetlicy możliwe po wcześniejszej rezerwacji u sołtysa lub opiekuna.\n2. W sali obowiązuje zakaz palenia tytoniu i spożywania alkoholu.\n3. Użytkownik odpowiada za porządek i stan wyposażenia po zakończeniu zajęć.\n4. Dzieci do lat 14 korzystają wyłącznie pod opieką dorosłego.\n5. W razie szkody należy niezwłocznie poinformować sołtysa lub gminę.",
  },
  { id: "kontakt", etykieta: "Kontakt / rezerwacja", typ: "text" as const, domysl: "Rezerwacja: sołtys {{wies}}, tel. …" },
  { id: "organizator", etykieta: "Stopka (sołectwo / gmina)", typ: "text" as const, domysl: "Sołectwo {{wies}} · Gmina {{gmina}}" },
];

const polaPlakatSwietlica = [
  { id: "naglowek", etykieta: "Nagłówek", typ: "text" as const, domysl: "Świetlica wiejska" },
  { id: "tytul", etykieta: "Tytuł", typ: "text" as const, domysl: "{{wies}} — zapraszamy!" },
  {
    id: "opis",
    etykieta: "Godziny / program / informacje",
    typ: "textarea" as const,
    domysl:
      "Godziny otwarcia:\npon.–pt. 16:00–20:00\nsob. 10:00–14:00\n\nZajęcia stałe:\n• Klub dziecięcy — wtorek 16:30\n• Klub seniora — czwartek 17:00\n• Zespół — piątek 18:00",
  },
  { id: "data", etykieta: "Od kiedy / data wydarzenia", typ: "date" as const, domysl: "" },
  { id: "godzina", etykieta: "Godzina", typ: "time" as const, domysl: "" },
  { id: "miejsce", etykieta: "Adres", typ: "text" as const, domysl: "ul. …, {{wies}}" },
  { id: "organizator", etykieta: "Zarządza / organizuje", typ: "text" as const, domysl: "Sołectwo {{wies}}" },
  { id: "kontakt", etykieta: "Kontakt", typ: "text" as const, domysl: "Sołtys: tel. …" },
];

/** Szablony Dnia Dziecka, zajęć dla dzieci i świetlicy wiejskiej. */
export const SZABLONY_SWIETLICA_DZIECI: SzablonGrafiki[] = [
  {
    id: "plakat-dzien-dziecka-kolorowy",
    kategoria: "plakaty",
    tytul: "Plakat — Dzień Dziecka (kolorowy)",
    opis: "Wesoły plakat z balonami — piknik, zabawy, animacje.",
    layout: "plakat-dzieci",
    format: "a4",
    orientacja: "pion",
    pola: polaPlakatDzieci,
    domyslnyMotyw: "dzieci-radosny",
    dostep: "wszyscy",
    tagi: ["plakat", "Dzień Dziecka", "dzieci", "wow"],
  },
  {
    id: "plakat-dzien-dziecka-swietlica",
    kategoria: "plakaty",
    tytul: "Plakat — Dzień Dziecka w świetlicy",
    opis: "Impreza dla najmłodszych w sali wiejskiej — animacje, konkursy, poczęstunek.",
    layout: "plakat-dzieci",
    format: "a4",
    orientacja: "pion",
    pola: [
      ...polaPlakatDzieci.slice(0, 2),
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea" as const,
        domysl:
          "🎭 Teatrzyk kukiełkowy\n🧁 Warsztaty cukiernicze\n🎯 Gry i konkursy w sali\n🎁 Upominki dla każdego dziecka",
      },
      ...polaPlakatDzieci.slice(3),
    ],
    domyslnyMotyw: "dzieci-radosny",
    dostep: "wszyscy",
    tagi: ["plakat", "Dzień Dziecka", "dzieci", "świetlica", "wow"],
  },
  {
    id: "plakat-konkurs-plastyczny-dzieci",
    kategoria: "plakaty",
    tytul: "Plakat — konkurs plastyczny dla dzieci",
    opis: "Ogłoszenie konkursu „Moja wieś oczami dziecka” lub tematycznego.",
    layout: "plakat-dzieci",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Hasło", typ: "text" as const, domysl: "Konkurs plastyczny!" },
      { id: "tytul", etykieta: "Temat konkursu", typ: "text" as const, domysl: "„Moja wieś oczami dziecka”" },
      {
        id: "opis",
        etykieta: "Zasady / kategorie",
        typ: "textarea" as const,
        domysl:
          "Kategorie wiekowe: 6–9 lat · 10–13 lat\nTechnika dowolna · format A4\nTermin oddania prac: …\nNagrody wręczymy podczas festynu!",
      },
      { id: "data", etykieta: "Termin konkursu / wręczenia", typ: "date" as const, domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time" as const, domysl: "16:00" },
      { id: "miejsce", etykieta: "Miejsce oddania / wręczenia", typ: "text" as const, domysl: "Szkoła / świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text" as const, domysl: "Sołectwo {{wies}} · Szkoła Podstawowa" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text" as const, domysl: "{{telefon}}" },
    ],
    domyslnyMotyw: "dzieci-radosny",
    dostep: "wszyscy",
    tagi: ["plakat", "dzieci", "konkurs", "szkoła"],
  },
  {
    id: "zaproszenie-warsztaty-dzieci",
    kategoria: "zaproszenia",
    tytul: "Zaproszenie — warsztaty dla dzieci",
    opis: "Ferie, wakacje, zajęcia plastyczne lub sportowe w świetlicy.",
    layout: "zaproszenie-nowoczesne",
    format: "a5",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text" as const, domysl: "Wakacyjne warsztaty!" },
      { id: "tytul", etykieta: "Nazwa zajęć", typ: "text" as const, domysl: "Kreatywne popołudnia w świetlicy" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea" as const,
        domysl: "Malowanie · origami · gry planszowe · mini olimpiada sportowa. Zajęcia bezpłatne — zapis u sołtysa.",
      },
      { id: "data", etykieta: "Data rozpoczęcia", typ: "date" as const, domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time" as const, domysl: "10:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text" as const, domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text" as const, domysl: "Sołectwo {{wies}} · GOPS" },
      { id: "kontakt", etykieta: "Zapisy", typ: "text" as const, domysl: "tel. …" },
    ],
    domyslnyMotyw: "dzieci-radosny",
    dostep: "wszyscy",
    tagi: ["zaproszenie", "dzieci", "świetlica", "wakacje"],
  },
  {
    id: "dyplom-super-dziecko",
    kategoria: "dyplomy",
    tytul: "Dyplom — wyróżnienie dla dziecka",
    opis: "Za aktywność w świetlicy, pomoc w festynie lub wyniki w konkursie.",
    layout: "dyplom-ozdobny",
    format: "a4",
    orientacja: "poziom",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text" as const, domysl: "Dyplom Super Dziecka" },
      { id: "tytul", etykieta: "Imię i nazwisko", typ: "text" as const, domysl: "…" },
      {
        id: "opis",
        etykieta: "Za co",
        typ: "textarea" as const,
        domysl: "Za aktywne uczestnictwo w zajęciach świetlicy, życzliwość wobec rówieśników i pomoc przy organizacji Dnia Dziecka.",
      },
      { id: "data", etykieta: "Data", typ: "date" as const, domysl: "" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text" as const, domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Nadaje", typ: "text" as const, domysl: "Sołectwo {{wies}}" },
      { id: "podpis1", etykieta: "Podpis — sołtys", typ: "text" as const, domysl: "Sołtys\n…" },
      { id: "podpis2", etykieta: "Podpis — opiekun", typ: "text" as const, domysl: "Opiekun świetlicy\n…" },
      { id: "podpis_cyfrowy", etykieta: "Podpis elektroniczny", typ: "text" as const, domysl: "" },
    ],
    domyslnyMotyw: "dzieci-radosny",
    dostep: "wszyscy",
    tagi: ["dyplom", "dzieci", "świetlica"],
  },
  {
    id: "karta-regulamin-swietlicy",
    kategoria: "karty",
    tytul: "Regulamin korzystania ze świetlicy",
    opis: "Karta do powieszenia przy wejściu — zasady użytkowania sali.",
    layout: "karta-regulamin",
    format: "a4",
    orientacja: "pion",
    pola: polaKartaRegulamin,
    domyslnyMotyw: "swietlica-ciepla",
    dostep: "soltys",
    tagi: ["świetlica", "regulamin", "informacja", "wow"],
  },
  {
    id: "karta-rezerwacja-swietlicy",
    kategoria: "karty",
    tytul: "Karta — rezerwacja sali / świetlicy",
    opis: "Zasady wypożyczania sali na urodziny, zebrania KGW lub spotkania.",
    layout: "karta-regulamin",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text" as const, domysl: "Rezerwacja świetlicy" },
      { id: "tytul", etykieta: "Podtytuł", typ: "text" as const, domysl: "Sołectwo {{wies}}" },
      {
        id: "opis",
        etykieta: "Zasady rezerwacji",
        typ: "textarea" as const,
        domysl:
          "1. Rezerwacji dokonuje się u sołtysa minimum 7 dni wcześniej.\n2. Sala dostępna dla mieszkańców sołectwa — urodziny, spotkania rodzinne, zebrania.\n3. Opłata: według uchwały rady sołeckiej / gminy (jeśli dotyczy).\n4. Po zakończeniu wydarzenia sala ma być posprzątana i włączone światło wyłączone.\n5. Klucze odbiera i zdaje osoba rezerwująca.",
      },
      { id: "kontakt", etykieta: "Rezerwacja / kontakt", typ: "text" as const, domysl: "Sołtys {{wies}} — tel. …" },
      { id: "organizator", etykieta: "Stopka", typ: "text" as const, domysl: "Gmina {{gmina}}" },
    ],
    domyslnyMotyw: "swietlica-ciepla",
    dostep: "soltys",
    tagi: ["świetlica", "regulamin", "rezerwacja"],
  },
  {
    id: "plakat-godziny-swietlicy",
    kategoria: "plakaty",
    tytul: "Plakat — godziny otwarcia świetlicy",
    opis: "Informacja o terminach otwarcia i stałych zajęciach.",
    layout: "plakat-swietlica",
    format: "a4",
    orientacja: "pion",
    pola: polaPlakatSwietlica,
    domyslnyMotyw: "swietlica-ciepla",
    dostep: "wszyscy",
    tagi: ["plakat", "świetlica", "informacja", "wow"],
  },
  {
    id: "plakat-zajecia-swietlicy",
    kategoria: "plakaty",
    tytul: "Plakat — zajęcia w świetlicy (harmonogram)",
    opis: "Tygodniowy rozkład klubu dziecięcego, seniorów, zespołu.",
    layout: "plakat-swietlica",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text" as const, domysl: "Harmonogram zajęć" },
      { id: "tytul", etykieta: "Tytuł", typ: "text" as const, domysl: "Świetlica {{wies}}" },
      {
        id: "opis",
        etykieta: "Plan tygodnia",
        typ: "textarea" as const,
        domysl:
          "PON — zajęcia komputerowe 17:00\nWT — klub dziecięcy 16:30\nŚR — warsztaty rękodzieła KGW 17:00\nCZW — klub seniora 17:00\nPT — próba zespołu 18:00\nSOB — otwarte drzwi dla rodzin 10:00–13:00",
      },
      { id: "data", etykieta: "Obowiązuje od", typ: "date" as const, domysl: "" },
      { id: "godzina", etykieta: "Godzina (opcjonalnie)", typ: "time" as const, domysl: "" },
      { id: "miejsce", etykieta: "Adres", typ: "text" as const, domysl: "Świetlica, {{wies}}" },
      { id: "organizator", etykieta: "Organizator", typ: "text" as const, domysl: "Sołectwo {{wies}} · Rada Sołecka" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text" as const, domysl: "Sołtys: tel. …" },
    ],
    domyslnyMotyw: "swietlica-ciepla",
    dostep: "wszyscy",
    tagi: ["plakat", "świetlica", "harmonogram"],
  },
  {
    id: "karta-bezpieczenstwo-swietlicy",
    kategoria: "karty",
    tytul: "Karta — bezpieczeństwo pożarowe w świetlicy",
    opis: "Zasady ewakuacji i zakazy — do powieszenia w widocznym miejscu.",
    layout: "karta-regulamin",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text" as const, domysl: "Bezpieczeństwo pożarowe" },
      { id: "tytul", etykieta: "Obiekt", typ: "text" as const, domysl: "Świetlica wiejska — {{wies}}" },
      {
        id: "opis",
        etykieta: "Instrukcja",
        typ: "textarea" as const,
        domysl:
          "• Wyjście ewakuacyjne: drzwi główne (patrz plan przy wejściu)\n• Gaśnica: przy drzwiach od strony kuchni\n• W razie alarmu — opuść budynek spokojnie, nie używaj windy\n• Miejsce zbiórki: parking przed świetlicą\n• Numer alarmowy: 112 · Straż Pożarna: 998",
      },
      { id: "kontakt", etykieta: "Odpowiedzialny", typ: "text" as const, domysl: "Sołtys / opiekun obiektu — tel. …" },
      { id: "organizator", etykieta: "Stopka", typ: "text" as const, domysl: "Sołectwo {{wies}}" },
    ],
    domyslnyMotyw: "swietlica-ciepla",
    dostep: "soltys",
    tagi: ["świetlica", "bezpieczeństwo", "OSP"],
  },
  {
    id: "zaproszenie-otwarcie-swietlicy",
    kategoria: "zaproszenia",
    tytul: "Zaproszenie — otwarcie / ponowne otwarcie świetlicy",
    opis: "Po remoncie, funduszu sołeckim lub nowym wyposażeniu.",
    layout: "zaproszenie-eleganckie",
    format: "a4",
    orientacja: "pion",
    pola: [
      { id: "naglowek", etykieta: "Nagłówek", typ: "text" as const, domysl: "Serdecznie zapraszamy" },
      { id: "tytul", etykieta: "Tytuł", typ: "text" as const, domysl: "Uroczyste otwarcie odnowionej świetlicy" },
      {
        id: "opis",
        etykieta: "Program",
        typ: "textarea" as const,
        domysl:
          "Po remoncie finansowanym ze środków sołeckich i wsparciu mieszkańców zapraszamy na wspólne otwarcie sali. W programie: pokaz nowego wyposażenia, poczęstunek, zabawy dla dzieci.",
      },
      { id: "data", etykieta: "Data", typ: "date" as const, domysl: "" },
      { id: "godzina", etykieta: "Godzina", typ: "time" as const, domysl: "17:00" },
      { id: "miejsce", etykieta: "Miejsce", typ: "text" as const, domysl: "Świetlica wiejska, {{wies}}" },
      { id: "organizator", etykieta: "Zaprasza", typ: "text" as const, domysl: "Sołectwo {{wies}} · Rada Sołecka" },
      { id: "kontakt", etykieta: "Kontakt", typ: "text" as const, domysl: "tel. …" },
    ],
    domyslnyMotyw: "swietlica-ciepla",
    dostep: "soltys",
    tagi: ["zaproszenie", "świetlica", "otwarcie"],
  },
];
